[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "dist/functions"

[site]
bucket = "dist/public"

[[redirects]]
from = "/api/*"
to = "/server.js"
status = 200
