[site]
name = "sage-movies"
compatibility_date = "2023-12-01"

[build]
command = "npm run build"
output_directory = "dist"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "functions"
