name = "sagemovies"
compatibility_date = "2023-12-01"
main = "dist/server.js"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "dist/public"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
vars = { NODE_ENV = "production" }
